import { addMonths, subMonths } from "date-fns";
import { buildIcs, calendarNames, icsResponse } from "@/lib/ics";
import { getServiceSupabase } from "@/lib/supabase/server";
import { isDemoMode } from "@/lib/demo";
import { sampleAppointments } from "@/lib/data/sample-admin";

/**
 * Tausha's private counselling schedule, as a calendar feed.
 *
 * Google Calendar can't send an Authorization header when it polls a URL, so
 * the secret has to live in the URL itself. That means:
 *   - the token is 24 random bytes, generated by the database
 *   - the response is marked no-store and noindex
 *   - a leaked URL is revoked by deleting the row in `calendar_tokens`
 *
 * Client names are included because this feed is for her eyes only. Treat the
 * URL like a password.
 */
export const dynamic = "force-dynamic";

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ token: string }> },
) {
  const { token } = await params;

  if (!token || token.length < 24) {
    return new Response("Not found", { status: 404 });
  }

  let appointments = sampleAppointments;

  if (!isDemoMode) {
    // Service key: this runs with no signed-in user, so the token IS the auth.
    const supabase = getServiceSupabase();
    if (!supabase) return new Response("Not found", { status: 404 });

    const { data: tokenRow } = await supabase
      .from("calendar_tokens")
      .select("id, kind")
      .eq("token", token)
      .eq("kind", "counselling")
      .maybeSingle();

    if (!tokenRow) return new Response("Not found", { status: 404 });

    const { data } = await supabase
      .from("counselling_appointments")
      .select("*")
      .gte("starts_at", subMonths(new Date(), 3).toISOString())
      .lte("starts_at", addMonths(new Date(), 12).toISOString());

    appointments = (data as typeof sampleAppointments) ?? [];
  }

  const body = buildIcs({
    name: calendarNames.counselling,
    description: "Private — counselling appointments.",
    refreshMinutes: 30,
    events: appointments.map((a) => ({
      uid: a.id,
      title: `${a.client_name} — ${a.kind.replace("_", " ")}`,
      location: a.location,
      start: new Date(a.starts_at),
      end: new Date(a.ends_at),
      cancelled: a.status === "cancelled",
    })),
  });

  const response = icsResponse(body, "counselling-schedule.ics");
  response.headers.set("Cache-Control", "no-store, private");
  response.headers.set("X-Robots-Tag", "noindex, nofollow");
  return response;
}
